---
- name: set hostname
  hostname: name={{ host }}

- name: add hostname in /etc/sysconfig/network
  lineinfile: >
    dest=/etc/sysconfig/network line='HOSTNAME={{ host }}'
    state=present create=yes
    owner=root group=root mode=0644

- name: add preserve_hostname in /etc/cloud/cloud.cfg
  lineinfile: >
    dest=/etc/cloud/cloud.cfg line='preserve_hostname: true'
    state=present create=yes
    owner=root group=root mode=0644
