---
- name: check if a cloudera manager server external database exists or not
  shell: >
    /usr/bin/mysql -h {{ scm_db_host }} -u{{ mysql_root_name }} -p{{ mysql_root_pass }}
    -e "SHOW DATABASES;"
  register: databases

- name: preparing a cloudera manager server external database
  shell: >
    /usr/share/cmf/schema/scm_prepare_database.sh mysql
    -u{{ mysql_root_name }} -p{{ mysql_root_pass }}
    {{ scm_db_name }} {{ scm_db_user }} {{ scm_db_pass }}
  when: databases.stdout.find('{{ scm_db_name }}') == -1 and
        "{{ scm_host }}" == "{{ scm_db_host }}"

- name: preparing a cloudera manager server external database
  shell: >
    /usr/share/cmf/schema/scm_prepare_database.sh mysql
    -h {{ scm_db_host }} -u{{ mysql_root_name }} -p{{ mysql_root_pass }}
    --scm-host {{ scm_host }}
    {{ scm_db_name }} {{ scm_db_user }} {{ scm_db_pass }}
  when: databases.stdout.find('{{ scm_db_name }}') == -1 and
        "{{ scm_host }}" != "{{ scm_db_host }}"
