---
depends:
  - apr
  - apr-util
  - psmisc
  - avahi-libs
  - cups-libs
  - cups-client
  - httpd-tools
  - perl-parent
  - perl-HTTP-Tiny
  - perl-podlators
  - perl-Pod-Perldoc
  - perl-Text-ParseWords
  - perl-Pod-Escapes
  - perl-Encode
  - perl-Pod-Usage
  - perl-libs
  - perl-macros
  - perl-Exporter
  - perl-constant
  - perl-Time-Local
  - perl-Socket
  - perl-Carp
  - perl-Time-HiRes
  - perl-PathTools
  - perl-Scalar-List-Utils
  - perl-Storable
  - perl-File-Temp
  - perl-File-Path
  - perl-threads-shared
  - perl-threads
  - perl-Filter
  - perl-Pod-Simple
  - perl-Getopt-Long
  - perl
  - cyrus-sasl-gssapi
  - time
  - libcom_err-devel
  - cyrus-sasl-plain
  - ed
  - mailx
  - spax
  - fuse
  - bind-libs
  - bind-utils
  - libxslt
  - at
  - patch
  - postgresql-libs
  - python-psycopg2
  - bc
  - libverto-devel
  - zlib-devel
  - fuse-libs
  - m4
  - pcre-devel
  - MySQL-python
  - mailcap
  - httpd
  - mod_ssl
  - libsepol-devel
  - libselinux-devel
  - keyutils-libs-devel
  - krb5-devel
  - openssl-devel
  - redhat-lsb-submod-security
  - redhat-lsb-core
