---
- hosts: cm
  become: yes
  become_method: sudo
  vars:
    rdbms: mysql

  pre_tasks:

  roles:
    - hostsfile
    - static-hostname
    - mysql-server
    - cloudera-manager
    - local-repository

  post_tasks:


- hosts: master
  become: yes
  become_method: sudo

  pre_tasks:

  roles:
    - hostsfile
    - static-hostname

  post_tasks:


- hosts: slave
  become: yes
  become_method: sudo

  pre_tasks:

  roles:
    - hostsfile
    - static-hostname

  post_tasks:
