---
- name: set timezone
  command: timedatectl set-timezone {{ ntp_timezone }}

- name: install ntp
  yum: name=ntp state=present

- name: ensure ntp is running and enabled at system start
  service: name=ntpd state=started enabled=yes
  when: ntp_enabled

- name: ensure ntp is stopped and disabled at system start
  service: name=ntpd state=stopped enabled=no
  when: not ntp_enabled
